stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: atriarch-halin:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.atriarch.systems
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: dan@mail.atriarch.systems
    notifier: c-xc9r9:n-g2gcc
  condition:
  - Failed
