stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: atriarch-halin:v1.0.${CICD_EXECUTION_SEQUENCE}
      registry: index.docker.io
timeout: 60
notification: {}
