version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers-legacy
    steps:
      - checkout
      - setup_remote_docker      
      - run:
          name: Prep
          command: |
            mkdir -p /tmp/artifacts
            sudo npm install -g yarn
            sudo apt-get update && sudo apt-get install -y s3cmd
      - run: 
          name: Build Halin Docker Image
          command: docker build -t mdavidallen/halin:latest -f Dockerfile .
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build JS
          command: npm run build
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn          
      - run:
          name: Start Neo4j 3.4.9 Enterprise
          command: |
            docker run -d --name neo4j-empty --rm -p 127.0.0.1:7474:7474 -p 127.0.0.1:7687:7687 --env NEO4J_AUTH=neo4j/admin --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes -t neo4j:3.4.9-enterprise
            sleep 20
            docker ps
            # docker exec neo4j-empty bin/cypher-shell -a localhost -u neo4j -p admin 'MATCH (n) RETURN count(n);' | true
            #while true; do 
            #  if curl -s -I http://localhost:7474 | grep "200 OK"; then
            #    echo "Neo4j up"
            #    break
            #  fi
            #  echo "Waiting for neo4j to come up"
            #  sleep 1 
            #done
            export NEO4J_URI=bolt://localhost:7687
            export NEO4J_USER=neo4j
            export NEO4J_PASSWORD=admin
            # yarn run gather

            docker run --network container:neo4j-empty \
              --env NEO4J_URI=bolt://localhost:7687 \
              --env NEO4J_USERNAME=neo4j \
              --env NEO4J_PASSWORD=admin \
              mdavidallen/halin:latest npm run gather > /tmp/artifacts/halin-output.txt
      - run:
          name: Deploy to S3
          command: |
            ENDPOINT=http://halin.s3-website-us-east-1.amazonaws.com
            BUCKET=halin
            BUILD=export BUILD=build-$CIRCLE_SHA1
            s3cmd put --recursive -P dist/* s3://$BUCKET/$BUILD
      - run:
          name: Deploy to Docker
          command: |
            export HALIN_VERSION=$(jq -r '.version' < package.json)
            export BUILD=build-$CIRCLE_SHA1
            echo "Build $BUILD"
            echo "Halin version is $HALIN_VERSION"            
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              echo "Pushing docker image"
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push mdavidallen/halin:latest

              docker tag mdavidallen/halin:latest mdavidallen/halin:$HALIN_VERSION
              docker push mdavidallen/halin:$HALIN_VERSION
            else
              echo "Not deploying; not master branch."
            fi
      - store_artifacts:
            path: /tmp/artifacts
      - store_artifacts:
            path: /home/circleci/.npm
